# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/cell-ribosome',
                'doc_host': 'https://binjian.xin.github.io',
                'git_url': 'https://github.com/binjian.xin/cell-ribosome',
                'lib_path': 'ribosome'},
  'syms': { 'ribosome.core': {'ribosome.core.foo': ('core.html#foo', 'ribosome/core.py')},
            'ribosome.gradio': {'ribosome.gradio.size': ('gradio.html#size', 'ribosome/gradio.py')}}}
