# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ribosome',
                'doc_host': 'https://Binjian.github.io',
                'git_url': 'https://github.com/Binjian/ribosome',
                'lib_path': 'ribosome'},
  'syms': {'ribosome.core': {'ribosome.core.foo': ('core.html#foo', 'ribosome/core.py')}}}
