//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Job.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJobListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class JobBaseListener : IJobListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProg([NotNull] JobParser.ProgContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.prog"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProg([NotNull] JobParser.ProgContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInst([NotNull] JobParser.InstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.inst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInst([NotNull] JobParser.InstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.instStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstStart([NotNull] JobParser.InstStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.instStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstStart([NotNull] JobParser.InstStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.instEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstEnd([NotNull] JobParser.InstEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.instEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstEnd([NotNull] JobParser.InstEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.copInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopInst([NotNull] JobParser.CopInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.copInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopInst([NotNull] JobParser.CopInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.operateExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperateExp([NotNull] JobParser.OperateExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.operateExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperateExp([NotNull] JobParser.OperateExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.numScalarOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumScalarOpExp([NotNull] JobParser.NumScalarOpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.numScalarOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumScalarOpExp([NotNull] JobParser.NumScalarOpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.copOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCopOpExp([NotNull] JobParser.CopOpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.copOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCopOpExp([NotNull] JobParser.CopOpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignOp([NotNull] JobParser.AssignOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.assignOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignOp([NotNull] JobParser.AssignOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.varIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarIndex([NotNull] JobParser.VarIndexContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.varIndex"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarIndex([NotNull] JobParser.VarIndexContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.baseInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseInst([NotNull] JobParser.BaseInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.baseInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseInst([NotNull] JobParser.BaseInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.clearInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClearInst([NotNull] JobParser.ClearInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.clearInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClearInst([NotNull] JobParser.ClearInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetInst([NotNull] JobParser.SetInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetInst([NotNull] JobParser.SetInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.intVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntVar([NotNull] JobParser.IntVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.intVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntVar([NotNull] JobParser.IntVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.floatVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatVar([NotNull] JobParser.FloatVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.floatVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatVar([NotNull] JobParser.FloatVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.numVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumVar([NotNull] JobParser.NumVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.numVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumVar([NotNull] JobParser.NumVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.strVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrVar([NotNull] JobParser.StrVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.strVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrVar([NotNull] JobParser.StrVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionVarScalar([NotNull] JobParser.PositionVarScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionVarScalar([NotNull] JobParser.PositionVarScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarCoordScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionVarCoordScalar([NotNull] JobParser.PositionVarCoordScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarCoordScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionVarCoordScalar([NotNull] JobParser.PositionVarCoordScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarJointScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionVarJointScalar([NotNull] JobParser.PositionVarJointScalarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarJointScalar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionVarJointScalar([NotNull] JobParser.PositionVarJointScalarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.iVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIVar([NotNull] JobParser.IVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.iVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIVar([NotNull] JobParser.IVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.hVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHVar([NotNull] JobParser.HVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.hVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHVar([NotNull] JobParser.HVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.bVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBVar([NotNull] JobParser.BVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.bVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBVar([NotNull] JobParser.BVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setExtAxisInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetExtAxisInst([NotNull] JobParser.SetExtAxisInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setExtAxisInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetExtAxisInst([NotNull] JobParser.SetExtAxisInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setPInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetPInst([NotNull] JobParser.SetPInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setPInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetPInst([NotNull] JobParser.SetPInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumber([NotNull] JobParser.NumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.number"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumber([NotNull] JobParser.NumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTnValue([NotNull] JobParser.TnValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tnValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTnValue([NotNull] JobParser.TnValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setFrameInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSetFrameInst([NotNull] JobParser.SetFrameInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setFrameInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSetFrameInst([NotNull] JobParser.SetFrameInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.str2iInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr2iInst([NotNull] JobParser.Str2iInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.str2iInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr2iInst([NotNull] JobParser.Str2iInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.str2rInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStr2rInst([NotNull] JobParser.Str2rInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.str2rInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStr2rInst([NotNull] JobParser.Str2rInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.i2strInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterI2strInst([NotNull] JobParser.I2strInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.i2strInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitI2strInst([NotNull] JobParser.I2strInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.r2strInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterR2strInst([NotNull] JobParser.R2strInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.r2strInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitR2strInst([NotNull] JobParser.R2strInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ioInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIoInst([NotNull] JobParser.IoInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ioInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIoInst([NotNull] JobParser.IoInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.digitalIOVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDigitalIOVar([NotNull] JobParser.DigitalIOVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.digitalIOVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDigitalIOVar([NotNull] JobParser.DigitalIOVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.outExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutExp([NotNull] JobParser.OutExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.outExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutExp([NotNull] JobParser.OutExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tDIS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTDIS([NotNull] JobParser.TDISContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tDIS"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTDIS([NotNull] JobParser.TDISContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.anInVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnInVar([NotNull] JobParser.AnInVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.anInVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnInVar([NotNull] JobParser.AnInVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.anOutVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnOutVar([NotNull] JobParser.AnOutVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.anOutVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnOutVar([NotNull] JobParser.AnOutVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.diVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiVar([NotNull] JobParser.DiVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.diVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiVar([NotNull] JobParser.DiVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giBVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGiBVar([NotNull] JobParser.GiBVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giBVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGiBVar([NotNull] JobParser.GiBVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giHVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGiHVar([NotNull] JobParser.GiHVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giHVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGiHVar([NotNull] JobParser.GiHVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giIVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGiIVar([NotNull] JobParser.GiIVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giIVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGiIVar([NotNull] JobParser.GiIVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giFVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGiFVar([NotNull] JobParser.GiFVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giFVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGiFVar([NotNull] JobParser.GiFVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.doVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDoVar([NotNull] JobParser.DoVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.doVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDoVar([NotNull] JobParser.DoVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goBVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoBVar([NotNull] JobParser.GoBVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goBVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoBVar([NotNull] JobParser.GoBVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goHVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoHVar([NotNull] JobParser.GoHVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goHVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoHVar([NotNull] JobParser.GoHVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goIVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoIVar([NotNull] JobParser.GoIVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goIVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoIVar([NotNull] JobParser.GoIVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goFVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGoFVar([NotNull] JobParser.GoFVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goFVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGoFVar([NotNull] JobParser.GoFVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.controlInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterControlInst([NotNull] JobParser.ControlInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.controlInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitControlInst([NotNull] JobParser.ControlInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.marcoFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMarcoFile([NotNull] JobParser.MarcoFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.marcoFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMarcoFile([NotNull] JobParser.MarcoFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.jobOrBackgroundFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJobOrBackgroundFile([NotNull] JobParser.JobOrBackgroundFileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.jobOrBackgroundFile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJobOrBackgroundFile([NotNull] JobParser.JobOrBackgroundFileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ifExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfExp([NotNull] JobParser.IfExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ifExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfExp([NotNull] JobParser.IfExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.opExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpExp([NotNull] JobParser.OpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.opExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpExp([NotNull] JobParser.OpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.whileExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileExp([NotNull] JobParser.WhileExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.whileExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileExp([NotNull] JobParser.WhileExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.whileOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileOpExp([NotNull] JobParser.WhileOpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.whileOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileOpExp([NotNull] JobParser.WhileOpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.multiConExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultiConExp([NotNull] JobParser.MultiConExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.multiConExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultiConExp([NotNull] JobParser.MultiConExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.conditionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConditionExp([NotNull] JobParser.ConditionExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.conditionExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConditionExp([NotNull] JobParser.ConditionExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.delayExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDelayExp([NotNull] JobParser.DelayExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.delayExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDelayExp([NotNull] JobParser.DelayExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.gotoExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGotoExp([NotNull] JobParser.GotoExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.gotoExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGotoExp([NotNull] JobParser.GotoExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.callExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCallExp([NotNull] JobParser.CallExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.callExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCallExp([NotNull] JobParser.CallExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.waitExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWaitExp([NotNull] JobParser.WaitExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.waitExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWaitExp([NotNull] JobParser.WaitExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.relationOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRelationOp([NotNull] JobParser.RelationOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.relationOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRelationOp([NotNull] JobParser.RelationOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.switchExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchExp([NotNull] JobParser.SwitchExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.switchExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchExp([NotNull] JobParser.SwitchExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.switchOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitchOpExp([NotNull] JobParser.SwitchOpExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.switchOpExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitchOpExp([NotNull] JobParser.SwitchOpExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.caseExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaseExp([NotNull] JobParser.CaseExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.caseExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaseExp([NotNull] JobParser.CaseExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.paracallExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParacallExp([NotNull] JobParser.ParacallExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.paracallExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParacallExp([NotNull] JobParser.ParacallExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.labelExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelExp([NotNull] JobParser.LabelExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.labelExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelExp([NotNull] JobParser.LabelExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.forExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForExp([NotNull] JobParser.ForExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.forExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForExp([NotNull] JobParser.ForExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.moveInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMoveInst([NotNull] JobParser.MoveInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.moveInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMoveInst([NotNull] JobParser.MoveInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.posGVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosGVar([NotNull] JobParser.PosGVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.posGVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosGVar([NotNull] JobParser.PosGVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.posLVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPosLVar([NotNull] JobParser.PosLVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.posLVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPosLVar([NotNull] JobParser.PosLVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPositionVar([NotNull] JobParser.PositionVarContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVar"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPositionVar([NotNull] JobParser.PositionVarContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.velocityAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVelocityAssign([NotNull] JobParser.VelocityAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.velocityAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVelocityAssign([NotNull] JobParser.VelocityAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.accAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccAssign([NotNull] JobParser.AccAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.accAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccAssign([NotNull] JobParser.AccAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.cntAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCntAssign([NotNull] JobParser.CntAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.cntAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCntAssign([NotNull] JobParser.CntAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.crAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCrAssign([NotNull] JobParser.CrAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.crAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCrAssign([NotNull] JobParser.CrAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.additionalInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAdditionalInst([NotNull] JobParser.AdditionalInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.additionalInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAdditionalInst([NotNull] JobParser.AdditionalInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.skipLaExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSkipLaExp([NotNull] JobParser.SkipLaExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.skipLaExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSkipLaExp([NotNull] JobParser.SkipLaExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.lhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLhAssign([NotNull] JobParser.LhAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.lhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLhAssign([NotNull] JobParser.LhAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.mhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMhAssign([NotNull] JobParser.MhAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.mhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMhAssign([NotNull] JobParser.MhAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.rhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRhAssign([NotNull] JobParser.RhAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.rhAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRhAssign([NotNull] JobParser.RhAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.operateInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOperateInst([NotNull] JobParser.OperateInstContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.operateInst"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOperateInst([NotNull] JobParser.OperateInstContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.irqOnExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIrqOnExp([NotNull] JobParser.IrqOnExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.irqOnExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIrqOnExp([NotNull] JobParser.IrqOnExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.irqOffExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIrqOffExp([NotNull] JobParser.IrqOffExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.irqOffExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIrqOffExp([NotNull] JobParser.IrqOffExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.levAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLevAssign([NotNull] JobParser.LevAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.levAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLevAssign([NotNull] JobParser.LevAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ufValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUfValue([NotNull] JobParser.UfValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ufValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUfValue([NotNull] JobParser.UfValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tfValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTfValue([NotNull] JobParser.TfValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tfValue"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTfValue([NotNull] JobParser.TfValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.fAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFAssign([NotNull] JobParser.FAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.fAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFAssign([NotNull] JobParser.FAssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTAssign([NotNull] JobParser.TAssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tAssign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTAssign([NotNull] JobParser.TAssignContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
