//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Job.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JobParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IJobListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProg([NotNull] JobParser.ProgContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.prog"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProg([NotNull] JobParser.ProgContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInst([NotNull] JobParser.InstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.inst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInst([NotNull] JobParser.InstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.instStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstStart([NotNull] JobParser.InstStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.instStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstStart([NotNull] JobParser.InstStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.instEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstEnd([NotNull] JobParser.InstEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.instEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstEnd([NotNull] JobParser.InstEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.copInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCopInst([NotNull] JobParser.CopInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.copInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCopInst([NotNull] JobParser.CopInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.operateExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperateExp([NotNull] JobParser.OperateExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.operateExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperateExp([NotNull] JobParser.OperateExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.numScalarOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumScalarOpExp([NotNull] JobParser.NumScalarOpExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.numScalarOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumScalarOpExp([NotNull] JobParser.NumScalarOpExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.copOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCopOpExp([NotNull] JobParser.CopOpExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.copOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCopOpExp([NotNull] JobParser.CopOpExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignOp([NotNull] JobParser.AssignOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.assignOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignOp([NotNull] JobParser.AssignOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.varIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarIndex([NotNull] JobParser.VarIndexContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.varIndex"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarIndex([NotNull] JobParser.VarIndexContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.baseInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBaseInst([NotNull] JobParser.BaseInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.baseInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBaseInst([NotNull] JobParser.BaseInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.clearInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClearInst([NotNull] JobParser.ClearInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.clearInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClearInst([NotNull] JobParser.ClearInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetInst([NotNull] JobParser.SetInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetInst([NotNull] JobParser.SetInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.intVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntVar([NotNull] JobParser.IntVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.intVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntVar([NotNull] JobParser.IntVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.floatVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatVar([NotNull] JobParser.FloatVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.floatVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatVar([NotNull] JobParser.FloatVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.numVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumVar([NotNull] JobParser.NumVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.numVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumVar([NotNull] JobParser.NumVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.strVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrVar([NotNull] JobParser.StrVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.strVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrVar([NotNull] JobParser.StrVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositionVarScalar([NotNull] JobParser.PositionVarScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositionVarScalar([NotNull] JobParser.PositionVarScalarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarCoordScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositionVarCoordScalar([NotNull] JobParser.PositionVarCoordScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarCoordScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositionVarCoordScalar([NotNull] JobParser.PositionVarCoordScalarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVarJointScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositionVarJointScalar([NotNull] JobParser.PositionVarJointScalarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVarJointScalar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositionVarJointScalar([NotNull] JobParser.PositionVarJointScalarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.iVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIVar([NotNull] JobParser.IVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.iVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIVar([NotNull] JobParser.IVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.hVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHVar([NotNull] JobParser.HVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.hVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHVar([NotNull] JobParser.HVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.bVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBVar([NotNull] JobParser.BVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.bVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBVar([NotNull] JobParser.BVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setExtAxisInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExtAxisInst([NotNull] JobParser.SetExtAxisInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setExtAxisInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExtAxisInst([NotNull] JobParser.SetExtAxisInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setPInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetPInst([NotNull] JobParser.SetPInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setPInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetPInst([NotNull] JobParser.SetPInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumber([NotNull] JobParser.NumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.number"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumber([NotNull] JobParser.NumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTnValue([NotNull] JobParser.TnValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tnValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTnValue([NotNull] JobParser.TnValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.setFrameInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetFrameInst([NotNull] JobParser.SetFrameInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.setFrameInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetFrameInst([NotNull] JobParser.SetFrameInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.str2iInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr2iInst([NotNull] JobParser.Str2iInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.str2iInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr2iInst([NotNull] JobParser.Str2iInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.str2rInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStr2rInst([NotNull] JobParser.Str2rInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.str2rInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStr2rInst([NotNull] JobParser.Str2rInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.i2strInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterI2strInst([NotNull] JobParser.I2strInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.i2strInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitI2strInst([NotNull] JobParser.I2strInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.r2strInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterR2strInst([NotNull] JobParser.R2strInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.r2strInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitR2strInst([NotNull] JobParser.R2strInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ioInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoInst([NotNull] JobParser.IoInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ioInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoInst([NotNull] JobParser.IoInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.digitalIOVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDigitalIOVar([NotNull] JobParser.DigitalIOVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.digitalIOVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDigitalIOVar([NotNull] JobParser.DigitalIOVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.outExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOutExp([NotNull] JobParser.OutExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.outExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOutExp([NotNull] JobParser.OutExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tDIS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTDIS([NotNull] JobParser.TDISContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tDIS"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTDIS([NotNull] JobParser.TDISContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.anInVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnInVar([NotNull] JobParser.AnInVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.anInVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnInVar([NotNull] JobParser.AnInVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.anOutVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnOutVar([NotNull] JobParser.AnOutVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.anOutVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnOutVar([NotNull] JobParser.AnOutVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.diVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDiVar([NotNull] JobParser.DiVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.diVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDiVar([NotNull] JobParser.DiVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giBVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGiBVar([NotNull] JobParser.GiBVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giBVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGiBVar([NotNull] JobParser.GiBVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giHVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGiHVar([NotNull] JobParser.GiHVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giHVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGiHVar([NotNull] JobParser.GiHVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giIVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGiIVar([NotNull] JobParser.GiIVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giIVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGiIVar([NotNull] JobParser.GiIVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.giFVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGiFVar([NotNull] JobParser.GiFVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.giFVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGiFVar([NotNull] JobParser.GiFVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.doVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoVar([NotNull] JobParser.DoVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.doVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoVar([NotNull] JobParser.DoVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goBVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoBVar([NotNull] JobParser.GoBVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goBVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoBVar([NotNull] JobParser.GoBVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goHVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoHVar([NotNull] JobParser.GoHVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goHVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoHVar([NotNull] JobParser.GoHVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goIVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoIVar([NotNull] JobParser.GoIVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goIVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoIVar([NotNull] JobParser.GoIVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.goFVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGoFVar([NotNull] JobParser.GoFVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.goFVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGoFVar([NotNull] JobParser.GoFVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.controlInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlInst([NotNull] JobParser.ControlInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.controlInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlInst([NotNull] JobParser.ControlInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.marcoFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMarcoFile([NotNull] JobParser.MarcoFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.marcoFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMarcoFile([NotNull] JobParser.MarcoFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.jobOrBackgroundFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJobOrBackgroundFile([NotNull] JobParser.JobOrBackgroundFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.jobOrBackgroundFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJobOrBackgroundFile([NotNull] JobParser.JobOrBackgroundFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ifExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfExp([NotNull] JobParser.IfExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ifExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfExp([NotNull] JobParser.IfExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.opExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpExp([NotNull] JobParser.OpExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.opExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpExp([NotNull] JobParser.OpExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.whileExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileExp([NotNull] JobParser.WhileExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.whileExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileExp([NotNull] JobParser.WhileExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.whileOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileOpExp([NotNull] JobParser.WhileOpExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.whileOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileOpExp([NotNull] JobParser.WhileOpExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.multiConExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiConExp([NotNull] JobParser.MultiConExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.multiConExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiConExp([NotNull] JobParser.MultiConExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.conditionExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConditionExp([NotNull] JobParser.ConditionExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.conditionExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConditionExp([NotNull] JobParser.ConditionExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.delayExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDelayExp([NotNull] JobParser.DelayExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.delayExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDelayExp([NotNull] JobParser.DelayExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.gotoExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoExp([NotNull] JobParser.GotoExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.gotoExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoExp([NotNull] JobParser.GotoExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.callExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallExp([NotNull] JobParser.CallExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.callExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallExp([NotNull] JobParser.CallExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.waitExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWaitExp([NotNull] JobParser.WaitExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.waitExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWaitExp([NotNull] JobParser.WaitExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.relationOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationOp([NotNull] JobParser.RelationOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.relationOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationOp([NotNull] JobParser.RelationOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.switchExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchExp([NotNull] JobParser.SwitchExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.switchExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchExp([NotNull] JobParser.SwitchExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.switchOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSwitchOpExp([NotNull] JobParser.SwitchOpExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.switchOpExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSwitchOpExp([NotNull] JobParser.SwitchOpExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.caseExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCaseExp([NotNull] JobParser.CaseExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.caseExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCaseExp([NotNull] JobParser.CaseExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.paracallExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParacallExp([NotNull] JobParser.ParacallExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.paracallExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParacallExp([NotNull] JobParser.ParacallExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.labelExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelExp([NotNull] JobParser.LabelExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.labelExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelExp([NotNull] JobParser.LabelExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.forExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForExp([NotNull] JobParser.ForExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.forExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForExp([NotNull] JobParser.ForExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.moveInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMoveInst([NotNull] JobParser.MoveInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.moveInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMoveInst([NotNull] JobParser.MoveInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.posGVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosGVar([NotNull] JobParser.PosGVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.posGVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosGVar([NotNull] JobParser.PosGVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.posLVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPosLVar([NotNull] JobParser.PosLVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.posLVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPosLVar([NotNull] JobParser.PosLVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.positionVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPositionVar([NotNull] JobParser.PositionVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.positionVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPositionVar([NotNull] JobParser.PositionVarContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.velocityAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVelocityAssign([NotNull] JobParser.VelocityAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.velocityAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVelocityAssign([NotNull] JobParser.VelocityAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.accAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccAssign([NotNull] JobParser.AccAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.accAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccAssign([NotNull] JobParser.AccAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.cntAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCntAssign([NotNull] JobParser.CntAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.cntAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCntAssign([NotNull] JobParser.CntAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.crAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCrAssign([NotNull] JobParser.CrAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.crAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCrAssign([NotNull] JobParser.CrAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.additionalInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditionalInst([NotNull] JobParser.AdditionalInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.additionalInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditionalInst([NotNull] JobParser.AdditionalInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.skipLaExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSkipLaExp([NotNull] JobParser.SkipLaExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.skipLaExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSkipLaExp([NotNull] JobParser.SkipLaExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.lhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLhAssign([NotNull] JobParser.LhAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.lhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLhAssign([NotNull] JobParser.LhAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.mhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMhAssign([NotNull] JobParser.MhAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.mhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMhAssign([NotNull] JobParser.MhAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.rhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRhAssign([NotNull] JobParser.RhAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.rhAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRhAssign([NotNull] JobParser.RhAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.operateInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOperateInst([NotNull] JobParser.OperateInstContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.operateInst"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOperateInst([NotNull] JobParser.OperateInstContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.irqOnExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIrqOnExp([NotNull] JobParser.IrqOnExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.irqOnExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIrqOnExp([NotNull] JobParser.IrqOnExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.irqOffExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIrqOffExp([NotNull] JobParser.IrqOffExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.irqOffExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIrqOffExp([NotNull] JobParser.IrqOffExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.levAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLevAssign([NotNull] JobParser.LevAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.levAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLevAssign([NotNull] JobParser.LevAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.ufValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUfValue([NotNull] JobParser.UfValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.ufValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUfValue([NotNull] JobParser.UfValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tfValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTfValue([NotNull] JobParser.TfValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tfValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTfValue([NotNull] JobParser.TfValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.fAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFAssign([NotNull] JobParser.FAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.fAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFAssign([NotNull] JobParser.FAssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JobParser.tAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTAssign([NotNull] JobParser.TAssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JobParser.tAssign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTAssign([NotNull] JobParser.TAssignContext context);
}
