/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 18
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 15
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_START = 1,
  anon_sym_END = 2,
  anon_sym_EQ = 3,
  anon_sym_X = 4,
  anon_sym_LBRACK = 5,
  anon_sym_RBRACK = 6,
  sym_INT = 7,
  sym_NEWLINE = 8,
  sym_SPACE = 9,
  sym_prog = 10,
  sym_stmt = 11,
  sym_assign = 12,
  sym_var = 13,
  aux_sym_prog_repeat1 = 14,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_START] = "START",
  [anon_sym_END] = "END",
  [anon_sym_EQ] = "=",
  [anon_sym_X] = "X",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_INT] = "INT",
  [sym_NEWLINE] = "NEWLINE",
  [sym_SPACE] = "SPACE",
  [sym_prog] = "prog",
  [sym_stmt] = "stmt",
  [sym_assign] = "assign",
  [sym_var] = "var",
  [aux_sym_prog_repeat1] = "prog_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_START] = anon_sym_START,
  [anon_sym_END] = anon_sym_END,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_X] = anon_sym_X,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_INT] = sym_INT,
  [sym_NEWLINE] = sym_NEWLINE,
  [sym_SPACE] = sym_SPACE,
  [sym_prog] = sym_prog,
  [sym_stmt] = sym_stmt,
  [sym_assign] = sym_assign,
  [sym_var] = sym_var,
  [aux_sym_prog_repeat1] = aux_sym_prog_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_START] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_END] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_X] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_INT] = {
    .visible = true,
    .named = true,
  },
  [sym_NEWLINE] = {
    .visible = true,
    .named = true,
  },
  [sym_SPACE] = {
    .visible = true,
    .named = true,
  },
  [sym_prog] = {
    .visible = true,
    .named = true,
  },
  [sym_stmt] = {
    .visible = true,
    .named = true,
  },
  [sym_assign] = {
    .visible = true,
    .named = true,
  },
  [sym_var] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_prog_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '\n', 16,
        '\r', 1,
        ' ', 17,
        '=', 11,
        'E', 4,
        'S', 6,
        'X', 12,
        '[', 13,
        ']', 14,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(16);
      END_STATE();
    case 2:
      if (lookahead == 'A') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'D') ADVANCE(10);
      END_STATE();
    case 4:
      if (lookahead == 'N') ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead == 'R') ADVANCE(7);
      END_STATE();
    case 6:
      if (lookahead == 'T') ADVANCE(2);
      END_STATE();
    case 7:
      if (lookahead == 'T') ADVANCE(9);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_START);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_END);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_X);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_INT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_NEWLINE);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_SPACE);
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_START] = ACTIONS(1),
    [anon_sym_END] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_X] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_INT] = ACTIONS(1),
    [sym_NEWLINE] = ACTIONS(1),
    [sym_SPACE] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_prog] = STATE(9),
    [anon_sym_START] = ACTIONS(5),
    [sym_SPACE] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(7), 1,
      anon_sym_END,
    ACTIONS(9), 1,
      anon_sym_X,
    STATE(12), 1,
      sym_assign,
    STATE(13), 1,
      sym_var,
    STATE(3), 2,
      sym_stmt,
      aux_sym_prog_repeat1,
  [20] = 6,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(9), 1,
      anon_sym_X,
    ACTIONS(11), 1,
      anon_sym_END,
    STATE(12), 1,
      sym_assign,
    STATE(13), 1,
      sym_var,
    STATE(4), 2,
      sym_stmt,
      aux_sym_prog_repeat1,
  [40] = 6,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(13), 1,
      anon_sym_END,
    ACTIONS(15), 1,
      anon_sym_X,
    STATE(12), 1,
      sym_assign,
    STATE(13), 1,
      sym_var,
    STATE(4), 2,
      sym_stmt,
      aux_sym_prog_repeat1,
  [60] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(18), 2,
      anon_sym_END,
      anon_sym_X,
  [68] = 3,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(9), 1,
      anon_sym_X,
    STATE(17), 1,
      sym_var,
  [78] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(20), 2,
      anon_sym_EQ,
      sym_NEWLINE,
  [86] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(22), 1,
      sym_NEWLINE,
  [93] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
  [100] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
  [107] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(28), 1,
      anon_sym_LBRACK,
  [114] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(30), 1,
      sym_NEWLINE,
  [121] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(32), 1,
      anon_sym_EQ,
  [128] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(34), 1,
      sym_INT,
  [135] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
  [142] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(38), 1,
      anon_sym_RBRACK,
  [149] = 2,
    ACTIONS(3), 1,
      sym_SPACE,
    ACTIONS(40), 1,
      sym_NEWLINE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 60,
  [SMALL_STATE(6)] = 68,
  [SMALL_STATE(7)] = 78,
  [SMALL_STATE(8)] = 86,
  [SMALL_STATE(9)] = 93,
  [SMALL_STATE(10)] = 100,
  [SMALL_STATE(11)] = 107,
  [SMALL_STATE(12)] = 114,
  [SMALL_STATE(13)] = 121,
  [SMALL_STATE(14)] = 128,
  [SMALL_STATE(15)] = 135,
  [SMALL_STATE(16)] = 142,
  [SMALL_STATE(17)] = 149,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_prog_repeat1, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_prog_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [18] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_stmt, 2, 0, 0),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var, 4, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [24] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 3, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prog, 4, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assign, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_test_simple(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "test_simple",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
