# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01.core.dom.ipynb.

# %% auto #0
__all__ = ['OLLAMA_API_KEY', 'DASHSCOPE_API_KEY', 'image_link_pattern', 'openai_client', 'ollama_client', 'chat_client', 'model',
           'msg_queue', 'resp_queue', 'lock', 'ResponseStatus', 'get_text_summary_response',
           'get_image_summary_response', 'get_text_summary_response_async', 'get_image_summary_response_async',
           'get_text_summary_response_openai_async', 'get_image_summary_response_openai_async',
           'get_summary_response_async', 'get_image_summary_async', 'AnalysisStatus', 'with_async_context', 'DOM',
           'analyze_one_document_async', 'embed_one_document_async']

# %% ../nbs/01.core.dom.ipynb #17235612
from fastcore.test import *
from fastcore.basics import patch

# %% ../nbs/01.core.dom.ipynb #745a9572
from typing import List, Optional, ClassVar, Callable
from pydantic import BaseModel, Field, field_validator
from functools import cached_property, wraps
import base64
import pypandoc
import pathlib
import asyncio
import tqdm
import json
import jsoncfg
import re
import os
from pathlib import Path
from pprint import pprint
import markdown
import asyncio 
import tqdm
import hashlib
from functools import cached_property
import chromadb
from chromadb.config import Settings
from chromadb import PersistentClient
from chromadb.api import AsyncClientAPI, ClientAPI
from chromadb.api.models.Collection import Collection
from enum import Enum
import warnings

# %% ../nbs/01.core.dom.ipynb #361567c2
from ollama import chat, ChatResponse, Client, AsyncClient
from openai import OpenAI, AsyncOpenAI

# %% ../nbs/01.core.dom.ipynb #f84bf070
from dotenv import load_dotenv
load_dotenv()
OLLAMA_API_KEY= os.getenv('OLLAMA_API_KEY')
print(OLLAMA_API_KEY)
DASHSCOPE_API_KEY= os.getenv('DASHSCOPE_API_KEY')
print(DASHSCOPE_API_KEY)

# %% ../nbs/01.core.dom.ipynb #ac94f2d9
def get_text_summary_response(content: str, model:str="gemma3-27b", role:str="user", lang: str="zh") -> ChatResponse:
    """Generate a text-summary chat response for the given content.
    
    Args:
        content: Source text to summarize.
        model: Chat model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        ChatResponse: Raw model response containing the summary.
    """
    match lang:
        case "en":
            prompt = (
                f"Please provide a summary of the following string. "
                f"The summary should be concise and informative: {content}. "
            )
        case "zh":
            content = re.sub(r"\s+", " ", content.strip())
            prompt = (
                f"请提供以下字符串的摘要。"
                f"摘要应简明扼要且信息丰富: {content}. "
            )
        case _:
            raise ValueError(f"Unsupported language: {lang}")
    return chat(
        model=model,
        messages=[
            {
                "role": role,
                "content": prompt,
            }
        ],
    )

# %% ../nbs/01.core.dom.ipynb #a2cb622f
image_link_pattern = r'[^\s]+\.(?:jpg|jpeg|png|gif|bmp|webp)'

def get_image_summary_response(image_link: str | Path, model:str="gemma3:27b", role:str="user", lang: str='zh') -> ChatResponse:
    """Generate an image-summary chat response for a local image path.
    
    Args:
        image_link: Image file path or path-like string.
        model: Vision model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        ChatResponse: Raw model response containing the summary.
    """
    if isinstance(image_link, Path):
        image_link = str(image_link)
    if not re.match(image_link_pattern, image_link):
        # If the image link is not a URL, throw an error
        raise ValueError(f"Invalid image link: {image_link}")
    
    match lang:
        case 'en':
            prompt = "Please provide a summary of the following image. The summary should be concise and informative about the robot."
        case 'zh':
            prompt = "请提供以下图像的摘要。关于机器人机械尺寸,运动范围,自由度的说明应简明扼要。"
        case _:
            raise ValueError(f"Unsupported language: {lang}")

    response = chat(
        model=model,
        messages=[
            {
                "role": role,
                "content": prompt,
                'images': [f"{image_link}"],
            }
        ],
    )
    return response


# %% ../nbs/01.core.dom.ipynb #9c0a8651
async def get_text_summary_response_async(client: AsyncClient, content: str, model:str="gemma3-27b", role:str="user", lang: str="zh") -> ChatResponse:
    """Generate a text-summary chat response with an async Ollama client.
    
    Args:
        client: Async Ollama client used to send the request.
        content: Source text to summarize.
        model: Chat model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        ChatResponse: Raw model response containing the summary.
    """
    content = re.sub(r"\s+", " ", content.strip())
    match lang:
        case "en":
            prompt = (
                f"Please provide a summary of the following string. "
                f"The summary should be concise and informative: {content}. "
            )
        case "zh":
            prompt = (
                f"请提供以下字符串的摘要。"
                f"摘要应简明扼要且信息丰富: {content}. "
            )
        case _:
            raise ValueError(f"Unsupported language: {lang}")
    
    message = {
        "role": role,
        "content": prompt,
    }
    response =  await client.chat(
        model=model,
        messages=[message],
    )
    return response

# %% ../nbs/01.core.dom.ipynb #222d20bc
image_link_pattern = r'[^\s]+\.(?:jpg|jpeg|png|gif|bmp|webp)'

async def get_image_summary_response_async(client: AsyncClient, image_link: str | Path, model:str="gemma3:27b", role:str="user", lang: str='zh') -> ChatResponse:
    """Generate an image-summary chat response with an async Ollama client.
    
    Args:
        client: Async Ollama client used to send the request.
        image_link: Image file path or path-like string.
        model: Vision model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        ChatResponse: Raw model response containing the summary.
    """
    if isinstance(image_link, Path):
        image_link = str(image_link)
    # if not re.match(image_link_pattern, image_link):
    #     # If the image link is not a URL, throw an error
    #     raise ValueError(f"Invalid image link: {image_link}")
    
    match lang:
        case 'en':
            prompt = "Please provide a summary of the following image. The summary should be concise and informative about the robot."
        case 'zh':
            prompt = "请提供以下图像的摘要。关于机器人机械尺寸,运动范围,自由度的说明应简明扼要。"
        case _:
            raise ValueError(f"Unsupported language: {lang}")

    response = await client.chat(
        model=model,
        messages=[
            {
                "role": role,
                "content": prompt,
                'images': [f"{image_link}"],
            }
        ],
    )
    return response


# %% ../nbs/01.core.dom.ipynb #b7f34b05
async def get_text_summary_response_openai_async(client: AsyncOpenAI, content: str, model:str="qwen-plus-2025-07-28", role:str="user", lang: str="zh") -> str:
    """Generate a text summary with an async OpenAI-compatible client.
    
    Args:
        client: Async OpenAI-compatible client used to send the request.
        content: Source text to summarize.
        model: Chat model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        str: Extracted summary text.
    """
    match lang:
        case "en":
            prompt = (
                f"Please provide a summary of the following string. "
                f"The summary should be concise and informative: {content}. "
            )
        case "zh":
            content = re.sub(r"\s+", " ", content.strip())
            prompt = (
                f"请提供以下字符串的摘要。"
                f"摘要应简明扼要且信息丰富: {content}. "
            )
        case _:
            raise ValueError(f"Unsupported language: {lang}")
    
    response = await client.chat.completions.create(
        model=model,
        messages=[{"role": role, "content": prompt}],
        extra_headers={"X-RateLimit-RPM": "60", "X-RateLimit-TPM": "1000000"}
    )
    
    return response.choices[0].message.content or ""

# %% ../nbs/01.core.dom.ipynb #1031999a
async def get_image_summary_response_openai_async(client: AsyncOpenAI, image_link: str | Path, model:str="qwen-vl-plus-2025-01-26", role:str="user", lang: str='zh') -> str:
    """Generate an image summary with an async OpenAI-compatible client.
    
    Args:
        client: Async OpenAI-compatible client used to send the request.
        image_link: Image file path or path-like string.
        model: Vision model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        str: Extracted summary text.
    """
    if isinstance(image_link, Path):
        image_link = str(image_link)
    if not re.search(image_link_pattern, image_link):
        raise ValueError(f"Invalid image link: {image_link}")
    
    # Read and encode image as base64
    import base64
    with open(image_link, "rb") as image_file:
        base64_image = base64.b64encode(image_file.read()).decode('utf-8')
    
    match lang:
        case 'en':
            prompt = "Please provide a summary of the following image. The summary should be concise and informative about the robot."
        case 'zh':
            prompt = "请提供以下图像的摘要。摘要应简明扼要，信息丰富，描述所显示的机器人内容。"
        case _:
            raise ValueError(f"Unsupported language: {lang}")
    
    response = await client.chat.completions.create(
        model=model,
        messages=[{
            "role": role,
            "content": [
                {"type": "text", "text": prompt},
                {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{base64_image}"}}
            ]
        }],
        extra_headers={"X-RateLimit-RPM": "60", "X-RateLimit-TPM": "1000000"}
    )
    
    return response.choices[0].message.content or ""

# %% ../nbs/01.core.dom.ipynb #4e4d97f2
async def get_summary_response_async(client: AsyncClient | AsyncOpenAI, content: str, model:str="gemma3:27b", role:str="user", lang: str="zh") -> str:
    """Route text summarization to the matching async client implementation.
    
    Args:
        client: Async Ollama or OpenAI-compatible client.
        content: Source text to summarize.
        model: Chat model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        str: Extracted summary text.
    """
    if isinstance(client, AsyncClient):
        # Ollama client
        response = await get_text_summary_response_async(client, content, model, role, lang)
        return response.message.content if hasattr(response, 'message') and hasattr(response.message, 'content') else ""
    elif isinstance(client, AsyncOpenAI):
        # OpenAI client
        return await get_text_summary_response_openai_async(client, content, model, role, lang)
    else:
        raise ValueError(f"Unsupported client type: {type(client)}")

# %% ../nbs/01.core.dom.ipynb #7b9eb566
async def get_image_summary_async(client: AsyncClient | AsyncOpenAI, image_link: str | Path, model:str="gemma3:27b", role:str="user", lang: str='zh') -> str:
    """Route image summarization to the matching async client implementation.
    
    Args:
        client: Async Ollama or OpenAI-compatible client.
        image_link: Image file path or path-like string.
        model: Vision model name to use.
        role: Message role sent to the model.
        lang: Prompt language code.
    
    Returns:
        str: Extracted summary text.
    """
    if isinstance(client, AsyncClient):
        # Ollama client
        response = await get_image_summary_response_async(client, image_link, model, role, lang)
        return response.message.content if hasattr(response, 'message') and hasattr(response.message, 'content') else ""
    elif isinstance(client, AsyncOpenAI):
        # OpenAI client  
        return await get_image_summary_response_openai_async(client, image_link, model, role, lang)
    else:
        raise ValueError(f"Unsupported client type: {type(client)}")

# %% ../nbs/01.core.dom.ipynb #bac42d51
# OpenAI client for text summarization 
openai_client = AsyncOpenAI(
    api_key=os.environ.get('DASHSCOPE_API_KEY'),
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"
)

# Ollama client for embeddings and image analysis
ollama_client = AsyncClient()

# For backward compatibility, keep chat_client pointing to OpenAI client
chat_client = openai_client

# %% ../nbs/01.core.dom.ipynb #4ee08de1
model = "deepseek-3.2v:cloud"  # "deepseek-r1:32b" "gemma3:27b"
if not ("cloud" in model):
    chat_client: AsyncClient = AsyncClient()   
else:
    chat_client = AsyncClient(
        host="http://ollama.com",
        headers={"Authorization": f"Bearer {os.environ.get('OLLAMA_API_KEY')}"}
        )
msg_queue: asyncio.Queue = asyncio.Queue(maxsize=8)  # Limit the queue size to 8 messages
resp_queue: asyncio.Queue = asyncio.Queue(maxsize=1)  # Limit the queue size to 1 message for response 
lock = asyncio.Lock()  # Lock to ensure thread-safe access to the queues

# %% ../nbs/01.core.dom.ipynb #c09ccfd1
model = "qwen-plus-2025-07-28"  #  "deepseek-v3.2"  #  
chat_client = AsyncOpenAI(
    api_key=os.environ.get('DASHSCOPE_API_KEY'),
    base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"
    )

# %% ../nbs/01.core.dom.ipynb #319435e8
ResponseStatus = Enum("ResponseStatus", ["PENDING", "PROCESSING", "REORGNIZED", "SEMANTICIZED", "CANCELLED", "COMPLETED", "ERROR"])
class AnalysisStatus:
    """
    Enum to represent the status of the analysis process.
    """
    status: ResponseStatus = Field(ResponseStatus.PENDING, description="Current status of the analysis process")
    exception: str = Field("", description="Exception message if any error occurs during analysis")

def with_async_context(context_builder: Callable[..., str]) -> Callable:
    """Wrap async helpers to append contextual information to unexpected errors."""
    def decorator(func: Callable) -> Callable:
        @wraps(func)
        async def wrapper(*args, **kwargs):
            try:
                return await func(*args, **kwargs)
            except ValueError:
                raise
            except Exception as exc:
                raise ValueError(f"{context_builder(*args, **kwargs)}\nError: {exc}") from exc
        return wrapper
    return decorator

# %% ../nbs/01.core.dom.ipynb #775311ac
from platform import node
from typing import Iterator, Callable, Optional, ClassVar
from queue import LifoQueue
import asyncio
import re
import copy
import jsoncfg
from jsoncfg.config_classes import ConfigJSONArray, ConfigJSONObject, ConfigJSONScalar, ConfigNode

class DOM(BaseModel):
    model_config = {"arbitrary_types_allowed": True}
    
    # The content of the Markdown document. This can be a string containing Markdown syntax.
    raw_markdown: Optional[str] = Field(None, description="Raw Markdown content")
    # raw json
    raw_json: Optional[str] = Field(None, description="Raw JSON content")
    # The json representation of the Markdown AST.
    ast_json: Optional[str] = Field(None, description="JSON representation of the Markdown AST")
    ast_json_file: Optional[Path] = Field(None, description="Path to the JSON file of the Markdown AST")
    semantics_json: Optional[str] = Field(None, description="Semantics JSON representation of the Markdown AST")
    semantics_json_file: Optional[Path] = Field(None, description="Path to the JSON file of the Markdown AST semantics")
    embed_json: Optional[str] = Field(None, description="Semantics JSON representation with embeddings and meta information of the Markdown AST")
    embed_json_file: Optional[Path] = Field(None, description="Path to the JSON file of the Markdown AST embeddings")
    file_path: Optional[Path] = Field(None, description="Path to the Markdown file")
    root_path: Path = Field(default_factory=Path, description="root path of the markdown document, required to get access to the images")
    table_count: int = Field(0, description="Number of tables in the Markdown document")
    section_count: int = Field(0, description="Number of headers in the Markdown document")
    section_level: list = Field(default_factory=list, description="List of section levels in the Markdown document")
    title:str = Field('', description="Title of the Markdown document, if available")
    ollama_client: AsyncClient = Field(default_factory=AsyncClient, description="AsyncClient instance for embeddings and image analysis (Ollama)")
    openai_client: AsyncOpenAI = Field(default_factory=lambda: AsyncOpenAI(api_key=os.environ.get('DASHSCOPE_API_KEY'), base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"), description="AsyncOpenAI instance for text summarization (OpenAI-compatible APIs)")
    db_client: ClientAPI = Field(default_factory=PersistentClient, description="PersistentClient instance for database interactions")
    analysis_status: AnalysisStatus = Field(default_factory=AnalysisStatus, description="Analysis status of the Markdown document")


    # Use ClassVar to indicate these are class variables, not instance fields
    TextBlock_Types: ClassVar[set[str]] = {
        "Plain",
        "Para",
        "Figure",
        "LineBlock","CodeBlock","RawBlock","OrderedList","BulletList","DefinitionList",
        "Header","BlockQuote",
        "Table","TableRow", "TableCell"}

    NonTextBlock_Types: ClassVar[set[str]] = {"HorizontalRule", "Div", "Null"}

    Embed_Types: ClassVar[set[str]] = {"Section", "Image", "Table"}

    Block_Types: ClassVar[set[str]] = TextBlock_Types.union(TextBlock_Types)

    Inline_Types: ClassVar[set[str]] = {
        "Str", "Emph", "Strong", "Strikeout", "Superscript", "Subscript",
        "Decimal", "Period",
        "Link", 
        "Image", "Code", "Math", "RawInline", "SoftBreak", "HardBreak", "Span"   
    }
    
    Element_Types: ClassVar[set[str]] = Block_Types | Inline_Types
    leaf_min_len: ClassVar[int] = 100  # Minimum length of text to consider for summarization

    _ARTIFACT_SUFFIXES: ClassVar[dict[str, str]] = {
        "ast_json_file": "_ast.json",
        "semantics_json_file": "_semantics.json",
        "embed_json_file": "_embed.json",
    }
    

    def __init__(self, md_file_path: Path, ollama_client: Optional[AsyncClient] = None, openai_client: Optional[AsyncOpenAI] = None, db_client: Optional[ClientAPI] = None, **data):
        """Initialize a DOM document wrapper for a markdown file.
        
        Args:
            md_file_path: Path to the source markdown file.
            ollama_client: Optional async Ollama client override.
            openai_client: Optional async OpenAI-compatible client override.
            db_client: Optional ChromaDB client override.
            **data: Additional model fields passed to `BaseModel`.
        """
        # Set defaults for data if not provided
        data.setdefault('file_path', Path(md_file_path))
        data.setdefault('root_path', Path(md_file_path).parent)
        data.setdefault('title', Path(md_file_path).stem)
        data.setdefault('ollama_client', ollama_client or AsyncClient())
        data.setdefault('openai_client', openai_client or AsyncOpenAI(api_key=os.environ.get('DASHSCOPE_API_KEY'), base_url="https://dashscope.aliyuncs.com/compatible-mode/v1"))
        data.setdefault('db_client', db_client or PersistentClient())
        data.setdefault('ast_json_file', None)
        data.setdefault('embed_json_file', None)
        data.setdefault('semantics_json_file', None)

        super().__init__(**data)

    def _artifact_path(self, suffix: str) -> Path:
        assert self.file_path is not None, "file_path is required to build artifact paths"
        return self.file_path.parent / f"{self.file_path.stem}{suffix}"

    def _sync_artifact_fields(self) -> None:
        for attr_name, suffix in self._ARTIFACT_SUFFIXES.items():
            setattr(self, attr_name, self._artifact_path(suffix))

    def _load_artifact(self, path_attr: str, content_attr: str) -> None:
        path = getattr(self, path_attr)
        if path and path.exists():
            setattr(self, content_attr, path.read_text(encoding="utf-8"))

    def _reset_document_state(self) -> None:
        self.raw_markdown = None
        self.raw_json = None
        self.ast_json = None
        self.semantics_json = None
        self.embed_json = None
        self.ast_json_file = None
        self.semantics_json_file = None
        self.embed_json_file = None

    def _require_action(self, action: Optional[Callable]) -> Callable:
        return action or self.__class__.identity

    def _render_markdown(self, target: str) -> str | None:
        if not self.raw_markdown:
            return None
        return pypandoc.convert_text(self.raw_markdown, target, "md")

    def _dump_json(self, value: dict | list) -> str:
        return json.dumps(value, ensure_ascii=False).encode("utf-8").decode("utf-8")

    def _map_tree(self, node, transform: Callable):
        node = transform(node)
        if isinstance(node, dict):
            for key, value in node.items():
                if isinstance(value, list):
                    node[key] = [
                        self._map_tree(child, transform)
                        if isinstance(child, (dict, list))
                        else child
                        for child in value
                    ]
                elif isinstance(value, dict):
                    node[key] = self._map_tree(value, transform)
        elif isinstance(node, list):
            node = [
                self._map_tree(child, transform) if isinstance(child, (dict, list)) else child
                for child in node
            ]
        return node

    async def _map_tree_async(self, node, transform: Callable, on_exit: Optional[Callable] = None):
        node = await transform(node)
        if isinstance(node, dict):
            for key, value in node.items():
                if isinstance(value, list):
                    node[key] = [
                        await self._map_tree_async(child, transform, on_exit)
                        if isinstance(child, (dict, list))
                        else child
                        for child in value
                    ]
                elif isinstance(value, dict):
                    node[key] = await self._map_tree_async(value, transform, on_exit)
        elif isinstance(node, list):
            node = [
                await self._map_tree_async(child, transform, on_exit) if isinstance(child, (dict, list)) else child
                for child in node
            ]

        if on_exit is not None:
            await on_exit(node)
        return node

    def _config_node_line(self, config_node: ConfigNode) -> int | str:
        try:
            return jsoncfg.node_location(config_node).line
        except Exception:
            return "unknown"

    def _config_error(self, message: str, config_node: ConfigNode, node=None) -> ValueError:
        details = [
            message,
            f"ConfigNode: {config_node} of type {type(config_node)}.",
            f"On line: {self._config_node_line(config_node)}",
        ]
        if node is not None:
            details.insert(1, f"Node: {node}")
        return ValueError("\n".join(details))

    async def _summarize_leaf_async(self, node: str, min_len: Optional[int] = None) -> str:
        text = str(node).strip()
        threshold = self.leaf_min_len if min_len is None else min_len
        if len(text) < threshold:
            return text

        response_content = await get_summary_response_async(
            self.openai_client,
            text,
            model='qwen-plus-2025-07-28',
            role="user",
            lang='zh',
        )
        return response_content or text

    async def _coerce_summary_async(self, value) -> str:
        if isinstance(value, str):
            return await self._summarize_leaf_async(value)
        if isinstance(value, (int, float)):
            return await self._summarize_leaf_async(str(value))
        if isinstance(value, dict):
            return value.get('s', '')
        if isinstance(value, list):
            return await self._summarize_list_async(value)
        if value is None:
            return ""
        raise ValueError(f"Unsupported element type: {type(value)} in {value}")

    async def _summarize_list_async(self, root: list) -> str:
        parts = [await self._coerce_summary_async(item) for item in root]
        merged = " ".join(part for part in parts if part)
        return await self._summarize_leaf_async(merged)

    def _document_metadata(self) -> dict[str, str]:
        if self.title is None:
            self.title = str(self.root_path)
        return {
            'title': self.title,
            'file_path': str(self.file_path),
        }

    async def _finalize_summary_ast_async(self, ast_dict: dict, blocks: list) -> str:
        ast_dict.update(self._document_metadata())
        dict_summary = [b['s'] for b in blocks if isinstance(b, dict) and 's' in b]
        dict_summary = [ast_dict['title']] + dict_summary
        ast_dict['summary'] = "" if not ast_dict['blocks'] or dict_summary == [] else await self._summarize_leaf_async(" ".join(dict_summary))
        serialized = self._dump_json(ast_dict)
        self.ast_json = serialized
        return serialized

    def _record_summary_progress(self, node_type: str, config_node: ConfigNode) -> None:
        if node_type == "Table":
            print(f"{self.file_path} Summarize table: {self.table_count} on line {self._config_node_line(config_node)}")
            self.table_count += 1
        elif node_type == "Section":
            print(f"{self.file_path} Summarize section: {self.section_count} on line {self._config_node_line(config_node)}")
            self.section_count += 1

    def _resolve_image_link(self, node: dict, config_node: ConfigNode) -> str:
        try:
            image_link = self.root_path / node['c'][2][0]
        except (IndexError, KeyError, TypeError) as exc:
            raise self._config_error("Invalid image node structure", config_node, node) from exc

        image_link = str(image_link)
        if not image_link or not re.search(image_link_pattern, image_link):
            raise self._config_error(f"Invalid image link: {image_link}", config_node, node)
        return image_link

    @with_async_context(lambda self, node, config_node: str(self._config_error("Error summarizing image node", config_node, node)))
    async def _summarize_image_node_async(self, node: dict, config_node: ConfigNode) -> dict:
        if not isinstance(node.get('c', []), list):
            raise self._config_error("Invalid image caption format", config_node, node)

        image_link = self._resolve_image_link(node, config_node)
        node["s"] = await get_image_summary_async(
            client=self.ollama_client,
            image_link=image_link,
            model="gemma3:27b",
            role="user",
            lang='zh'
        )
        print(f"Summarize image: {image_link} on line {self._config_node_line(config_node)}")
        return node


# %% ../nbs/01.core.dom.ipynb #72ff32e4
@patch
def setup(self: DOM):
    """Load markdown content and initialize cached AST, semantics, and embedding artifacts.
    
    Args:
        None.
    """
    content = self.file_path.read_text(encoding="utf-8")  # type: ignore
    if not content:
        self._reset_document_state()
        return

    self.raw_markdown = content
    self.raw_json = pypandoc.convert_text(self.raw_markdown, "json", "md")
    self._sync_artifact_fields()

    if self.ast_json_file and self.ast_json_file.exists():
        self.ast_json = self.ast_json_file.read_text(encoding="utf-8")
    else:
        print(f"--- IGNORE --- {self.file_path}")
        slide_splitter = r"(^<!--\s*Slide number:\s*\d+\s*-->$)"
        has_slides = re.search(slide_splitter, self.raw_markdown, flags=(re.MULTILINE | re.IGNORECASE))
        self.ast_json = self.reorg_slides(slide_splitter=slide_splitter) if has_slides else self.reorg()
        if self.ast_json_file:
            self.ast_json_file.write_text(self.ast_json, encoding="utf-8")

    self._load_artifact("semantics_json_file", "semantics_json")
    self._load_artifact("embed_json_file", "embed_json")


# %% ../nbs/01.core.dom.ipynb #cdd67649
@patch
def reorg_slides(self: DOM, slide_splitter: str = r"(^<!--\s*Slide number:\s*\d+\s*-->$)") -> str:
    """Split slide-delimited markdown into section-shaped AST nodes.
    
    Args:
        slide_splitter: Regular expression used to detect slide separators.
    
    Returns:
        str: Reorganized AST serialized as JSON.
    """

    assert self.raw_json or self.raw_markdown, "raw_json/raw_markdown content is empty. Cannot reorganize slides."
    # Split the raw_markdown into slides
    items = re.split(slide_splitter, self.raw_markdown, flags=re.MULTILINE)  # type: ignore
    presentation = json.loads(self.raw_json)  # type: ignore
    presentation['blocks'] = []  # type: ignore
    slide_header0 = {
        't': 'Section', 
        'c': [
            {
                't': 'Header', 
                'c': [
                    1,  # Header level, can be 1, 2, 3, etc.
                    ['slide header', [], []],  # The header format list [id, formtat1, format2]
                    [{'t': 'Str', 'c': 'slide header'}],  # The header content list
                ]
            },  # Header for the slide
            {
                't': 'Content', 
                'c': []
            }
            ]  # Content of the slide
        }
    # Reorganize each slide
    slide_header = None  # Initialize slide variable
    if items[0] == "":
        # If the first slide is empty, remove it
        items = items[1:]
        slide_header = copy.deepcopy(slide_header0)
        slide_header['c'][0]['c'][1][0] = '<!-- Slide number: 0 -->'
        slide_header['c'][0]['c'][2][0]['c'] = '<!-- Slide number: 0 -->'

    for item in items:
        if re.match(r"^<!--\s*Slide number:\s*\d+\s*-->$", item):
            # If the slide is a slide splitter
            slide_header = copy.deepcopy(slide_header0)  # must be deepcopy, otherwise the slide will be modified in place
            slide_header['c'][0]['c'][1][0] = item.strip()
            slide_header['c'][0]['c'][2][0]['c'] = item.strip()
        else:
            assert slide_header, f"Slide is not defined!"
            raw_ast = pypandoc.convert_text(item.strip(), "json", "md")
            ast = json.loads(raw_ast)
            assert ast.get('blocks'), f"AST blocks are not defined in {ast}"
            it = iter(ast['blocks'])
            slide, it = self.reorg_section(slide_header, it, bIgnoreLevel=True)         
            presentation['blocks'].append(slide)

    # Convert the list of slides back to a single JSON object
    return json.dumps(presentation, ensure_ascii=False).encode("utf-8").decode("utf-8")


# %% ../nbs/01.core.dom.ipynb #8360f0df
@patch
def to_markdown(self: DOM) -> str | None:
    """Return the raw markdown content for the current document.
    
    Args:
        None.
    
    Returns:
        str | None: Stored markdown text, if available.
    """
    return self.raw_markdown


# %% ../nbs/01.core.dom.ipynb #9d9c79f7
@patch
def to_html(self: DOM) -> str | None:
    """Render the current markdown content to HTML.
    
    Args:
        None.
    
    Returns:
        str | None: Rendered HTML, or `None` when no markdown is loaded.
    """
    return self._render_markdown("html")


# %% ../nbs/01.core.dom.ipynb #18088f36
@patch
def to_latex(self: DOM) -> str | None:
    """Render the current markdown content to LaTeX.
    
    Args:
        None.
    
    Returns:
        str | None: Rendered LaTeX, or `None` when no markdown is loaded.
    """
    return self._render_markdown("latex")


# %% ../nbs/01.core.dom.ipynb #b5f8328d
@patch
def to_json(self: DOM) -> str | None:
    """Return the serialized Pandoc AST for the current document.
    
    Args:
        None.
    
    Returns:
        str | None: Stored AST JSON, if available.
    """
    return self.raw_json


# %% ../nbs/01.core.dom.ipynb #7a47f6c4
@patch
async def embed(self: DOM, action: Optional[Callable] = None, db_path: Optional[Path] = Path("../db")) -> str:
    """Embed summarized semantic nodes and persist the embedding JSON output.
    
    Args:
        action: Optional transform applied to each node before traversal.
        db_path: Path to the persistent Chroma database directory.
    
    Returns:
        str: Serialized embedding JSON for the document.
    """
    if not self.semantics_json:
        raise ValueError("semantics_json content is empty. Cannot embed the content.")
    action = self._require_action(action)

    if self.embed_json:
        # If embed_json is already set, we don't need to walk the AST again
        print("embed_json is already set. Skipping walk.")
        return self.embed_json

    ast = json.loads(self.semantics_json)  # type: ignore

    assert isinstance(ast, dict), f"AST should be a dictionary, got {type(ast)}"
    canonical_json = json.dumps(ast, 
                                sort_keys=True, 
                                ensure_ascii=False,
                                separators=(',', ';')
                                ).encode("utf-8").decode("utf-8")
    full_canonical_string = str(self.file_path) + canonical_json
    # Create a unique ID for the AST based on its content
    ast['i'] = hashlib.sha256(full_canonical_string.encode("utf-8")).hexdigest()
    response = await self.ollama_client.embed(model="bge-m3", input=ast.get('summary', ''))  # Initialize the embedding list
    ast['e'] = response.embedding  # type: ignore
    cur_object_path = [ast['i']]  # Initialize the current object path with the AST ID
    ast['m'] = {
        'obj_path': list(cur_object_path),
        'embed_model': 'bge-m3',  # type: ignore
    }

    self.db_client = PersistentClient(path=db_path, settings=Settings(allow_reset=True))  # type: ignore
    # Create or get the collection in the database 'mitochondria'
    # collection = self.db_client.get_or_create_collection(name="mitochondria")  # defined in the closure for embed_node
    # Create or get the 'mitochondria' collection 'mitochondria' in the ephemeral database for testing purposes, to be commented out
    ephemeral_db_client = chromadb.EphemeralClient()  # type: ignore     
    assert ephemeral_db_client, "Failed to create ephemeral ChromaDB client."
        # defined in the closure for embed_node
    collection = ephemeral_db_client.get_or_create_collection(name="mitochondria")
    assert collection, "Failed to create or get the 'mitochondria' collection in the database."        
    collection.add(
        ids=[ast['i']],
        metadatas=[ast['m']],
        embeddings=ast['e'],  # type: ignore
        documents=[ast.get('summary', '')]
    )

    async def embed_node(node: dict) -> dict:
        """embeds the node summary text"""
        nonlocal collection, cur_object_path  # declare the collection variable in the closure
        
        assert node.get('t') in self.Embed_Types, f"Node type {node.get('t')} is not in Embed_Types: {self.Embed_Types}"
        # assert node.get('s'), f"Node summary text is empty for node: {node}"
        
        canonical_string = json.dumps(node, 
                                    sort_keys=True, 
                                    ensure_ascii=False,
                                    separators=(',',';')
                                ).encode("utf-8").decode("utf-8")
        # Create a unique ID for the node based on its content
        full_canonical_string = str(cur_object_path) + canonical_string

        # Create the identifier for the node
        # The identifier is a SHA256 hash of the full canonical string
        # This ensures that the identifier is unique and consistent for the same content
        node['i'] = hashlib.sha256(full_canonical_string.encode("utf-8")).hexdigest()
        # Create the embedding for the node summary
        response = await self.ollama_client.embed(model="bge-m3", input=node.get('s', ''))
        node['e'] = response.embedding  # type: ignore
        # Add meta information
        node['m'] = {
            'obj_path': list(cur_object_path),  # type: ignore
            'embed_model' : response.model,  # type: ignore
        }
        collection.add(
            ids=[node['i']],
            metadatas=[node['m']],
            embeddings=node['e'],  # type: ignore
            documents=[node.get('summary', '')]
        )

        return node

    async def enter_node(node):
        nonlocal cur_object_path
        node = action(node)
        if isinstance(node, dict) and node.get('t') in self.Embed_Types:
            node = await embed_node(node)
            cur_object_path.append(node.get('i', ''))
        return node

    async def leave_node(node):
        nonlocal cur_object_path
        if isinstance(node, dict) and node.get('t') in self.Embed_Types and len(cur_object_path) > 1:
            node_id = node.get('i')
            if cur_object_path[-1] == node_id:
                cur_object_path.pop()

    ast = await self._map_tree_async(ast, enter_node, on_exit=leave_node)
    self.embed_json = self._dump_json(ast)
    embed_json_file = self._artifact_path("_embed.json")
    with open(embed_json_file, "w", encoding="utf-8") as f:
        f.write(self.embed_json)
    return self.embed_json


# %% ../nbs/01.core.dom.ipynb #8d15b6f5
@patch
def walk_nodes_with_line_number(self: DOM, action: Optional[Callable] = None) -> None:
    """Walk the AST config structure and print node locations by source line.
    
    Args:
        action: Optional transform applied to each visited node.
    """
    if not self.raw_json:
        raise ValueError("raw_json content is empty. Cannot walk the AST.")
    if action is None:
        action = self.__class__.identity

    ast = jsoncfg.load_config(str(self.ast_json_file))

    def walk_node_obj(node)->None:
        node = action(node)
        if isinstance(node, ConfigJSONObject):
            # Dictionary
            for key, value in node:
                print(f"key   \"{key}\" at line {jsoncfg.node_location(value).line}")
                walk_node_obj(value)
        elif isinstance(node, ConfigJSONArray):
            # Array
            for item in node:
                walk_node_obj(item)
        elif isinstance(node, ConfigJSONScalar):
            # Scalar
            value = node()
            if isinstance(value, str):
                value = value.strip()
            print(f"value \"{value}\" at line {jsoncfg.node_location(node).line}")
        else:
            raise ValueError(f"Unknown node type: {type(node)}")

    ast = walk_node_obj(ast)


# %% ../nbs/01.core.dom.ipynb #019f19fa
@patch
def walk(self: DOM, action: Optional[Callable] = None) -> None:
    """Walk the raw AST and optionally transform each node in place.
    
    Args:
        action: Optional transform applied to each visited node.
    """
    if not self.raw_json:
        raise ValueError("raw_json content is empty. Cannot walk the AST.")
    action = self._require_action(action)

    ast = json.loads(self.raw_json)
    ast = self._map_tree(ast, action)
    self.ast_json = self._dump_json(ast)


# %% ../nbs/01.core.dom.ipynb #93e3a402
@patch
def reorg_section(self: DOM, section: dict, it: Iterator, bIgnoreLevel:bool=False) -> tuple[dict, Iterator]:
    """Pack following nodes into a section until a sibling or parent section is reached.
    
    Args:
        section: Section node being populated.
        it: Iterator over remaining sibling nodes.
        bIgnoreLevel: Whether to ignore section-level boundary checks.
    
    Returns:
        tuple[dict, Iterator]: Updated section and iterator for the remaining nodes.
    """

    assert section.get('t') == "Section", "Expected a Section node"
    level = section['c'][0]['c'][0]

    while True:
        try:
            item = next(it)
            if not bIgnoreLevel and isinstance(item, dict) and item.get('t') == "Section":
                # If the item is a Section, add the next items into its Content until the next Section
                next_level = item['c'][0]['c'][0]
                if next_level >= level + 1:  # lower levels need to be continuous
                    # If the next Section is at a lower level, step into further subsection handling
                    item, it = self.reorg_section(item, it, bIgnoreLevel=False)
                elif next_level == level:  # lower levels need to be continuous
                    # If the next Section is at the same level, we can stop here at the current recursion level
                    it = iter([item] + list(it))
                    return section, it
                    # item, it = reorg_section(item, it)
                elif next_level < level:  # higher levels don't need to be continuous
                    # If the next Section is at a higher level, we can stop here at the current recursion level
                    it = iter([item] + list(it))
                    return section, it
                else:  # next_level >= level + 2:
                    raise ValueError(f"Unexpected Section level encountered: node: {item}")

            # If the item is not a Section, we can add it to the Content of the Section
            assert section['c'][1].get('t') == "Content", "Expected a Content node"
            section['c'][1]['c'].append(item)

        except StopIteration:
            break
    return section, it


# %% ../nbs/01.core.dom.ipynb #cf39cc6a
@patch
def reorg(self: DOM, action: Optional[Callable] = None) -> str:
    """Convert header-based AST blocks into nested section structures.
    
    Args:
        action: Optional transform applied to each visited node.
    
    Returns:
        str: Reorganized AST serialized as JSON.
    """
    if not self.raw_json:
        raise ValueError("raw_json content is empty. Cannot walk the AST.")
    action = self._require_action(action)

    ast = json.loads(self.raw_json)

    
    def reorg_node(node):
        """Reorganizes the node structure to ensure that headers are treated as sections."""
        node = action(node)     

        if isinstance(node, dict):
            for key, value in node.items():
                if isinstance(value, list):
                    new_list = []
                    for child in value:
                        if isinstance(child, (dict, list)):
                            new_list.append(reorg_node(child))
                        else:
                            new_list.append(child)
                        if isinstance(child, dict):
                            # If the child is a dict, check if it has a 't' key
                            if 't' in child:
                                t = child['t']
                                if t == "Header":
                                    # If the node is a Header, create a new section 
                                    # and include the header in its content 
                                    # along with the following nodes until the next Header
                                    child['t'] = "Section"
                                    child['c'] = [
                                        {
                                            't': 'Header',
                                            'c': [
                                                child['c'][0],  # Header level
                                                child['c'][1],  # Header content
                                                child['c'][2],  # Header content
                                            ]
                                        },
                                        {
                                            't': 'Content',
                                            'c': []
                                        }
                                    ]
                                    self.section_level.append(child['c'][0]['c'][0])  # Append the header level to section_levell
                    it = iter(new_list)
                    new_value = []
                    while True:
                        try:
                            item = next(it)
                            if isinstance(item, dict) and item.get('t') == "Section":  # the first recursion level *
                                item, it = self.reorg_section(item,it, bIgnoreLevel=False)
                            new_value.append(item)
                        except StopIteration:
                            break
                    node[key] = new_value
                elif isinstance(value, dict):
                    node[key] = reorg_node(value)
        elif isinstance(node, list):
            node = [
                reorg_node(child) if isinstance(child, (dict, list)) else child
                for child in node
            ]
        return node

    ast = reorg_node(ast)
    return self._dump_json(ast)


# %% ../nbs/01.core.dom.ipynb #82250ea8
@patch
async def textualize(self: DOM, action: Optional[Callable] = None) -> None:
    """Summarize AST nodes into semantic text fields for downstream embedding.
    
    Args:
        action: Optional transform applied to each visited node.
    """
    if not self.ast_json:
        raise ValueError("raw_json content is empty. Cannot walk the AST and summarize.")
    action = self._require_action(action)

    @with_async_context(lambda config_node, node: str(self._config_error("Error summarizing node", config_node, node)))
    async def summary_node_pair_async(
        config_node: ConfigNode,
        node: dict | list | str | int | float | bool | None,
    ) -> tuple[ConfigNode, dict | list | str | int | float | bool | None]:
        node = action(node)

        if isinstance(node, dict):
            if not isinstance(config_node, ConfigJSONObject):
                raise self._config_error(f"Expected ConfigJSONObject, got {type(config_node)}", config_node, node)

            t = node.get("t")
            if t is None:
                raise self._config_error("Node does not have a 't' key", config_node, node)

            if t == "Image":
                node = await self._summarize_image_node_async(node, config_node)
            elif t in {"Cite", "AlignDefault", "ColWidth"}:
                node["s"] = ""
            else:
                content = node.get("c")
                if not content:
                    node["s"] = ""
                else:
                    dict_summary = []
                    for (_, cvalue), (key, value) in zip(config_node, node.items()):
                        if key == "t":
                            continue
                        if isinstance(cvalue, ConfigJSONArray):
                            if not isinstance(value, list):
                                raise self._config_error(f"Expected a list for key {key}, got {type(value)}", cvalue, value)
                            if not value:
                                continue
                            children = []
                            for citem, item in zip(cvalue, value):
                                _, child = await summary_node_pair_async(citem, item)
                                children.append(child)
                            node[key] = children
                            dict_summary.append(await self._summarize_list_async(children))
                        elif isinstance(cvalue, ConfigJSONObject):
                            if not isinstance(value, dict):
                                raise self._config_error(f"Expected a dict for key {key}, got {type(value)}", cvalue, value)
                            _, child = await summary_node_pair_async(cvalue, value)
                            node[key] = child
                            if isinstance(child, dict) and 's' in child:
                                dict_summary.append(child['s'])
                        elif value is None or value == "":
                            continue
                        elif isinstance(cvalue, ConfigJSONScalar):
                            if not isinstance(value, (str, int, float, bool)):
                                raise self._config_error(f"Expected a scalar for key {key}, got {type(value)}", cvalue, value)
                            dict_summary.append(await self._summarize_leaf_async(str(value)))

                    joined_summary = " ".join(part for part in dict_summary if part)
                    node["s"] = await self._summarize_leaf_async(joined_summary) if joined_summary else ""

                self._record_summary_progress(t, config_node)

        elif isinstance(node, list):
            if not isinstance(config_node, ConfigJSONArray):
                raise self._config_error(f"Expected ConfigJSONArray, got {type(config_node)}", config_node, node)
            new_node = []
            for citem, item in zip(config_node, node):
                if isinstance(item, (dict, list)):
                    _, child = await summary_node_pair_async(citem, item)
                elif isinstance(item, (str, int, float, bool)):
                    child = str(item).strip()
                else:
                    child = item
                new_node.append(child)
            node = new_node

        elif isinstance(node, (str, int, float, bool)):
            if not isinstance(config_node, ConfigJSONScalar):
                raise self._config_error(f"Expected ConfigJSONScalar, got {type(config_node)}", config_node, node)
            node = await self._summarize_leaf_async(str(node))
        elif node is not None:
            raise self._config_error(f"Unsupported node type: {type(node)}", config_node, node)

        return config_node, node

    config_ast = jsoncfg.load_config(str(self.ast_json_file))
    ast_dict = json.loads(self.ast_json)
    if not isinstance(config_ast, ConfigJSONObject):
        raise ValueError(f"AST should be a dictionary, got {type(config_ast)}")

    config_blocks = config_ast['blocks']
    blocks = ast_dict['blocks']
    _, blocks = await summary_node_pair_async(config_blocks, blocks)
    ast_dict['blocks'] = blocks
    await self._finalize_summary_ast_async(ast_dict, blocks)
    return
    async def get_leaf_summary_async(node:str, min_len:int) -> str: # If the string length is less than 200, return the node as is
        if len(node) < min_len:
            return node
        # If the node is not an image link, return a summary of the text using unified function
        response_content = await get_summary_response_async(self.openai_client, node, model='qwen-plus-2025-07-28', role="user", lang='zh')
        if response_content:
            return response_content
        else:
            # If the response is empty, return the original node
            return node

    async def get_list_summary_async(root: list) -> str:
        """
        Given a list of strings, return a summary of the list.
        If the list is empty, return an empty string.
        If the list has only one element, return the summary of that element.
        If the list has more than one element, return a summary of the concatenated elements.
        """
        list_summary = []
        for n in root:
            if isinstance(n, str):
                # If the element is a string, get its summary
                summary = await get_leaf_summary_async(n, min_len=self.leaf_min_len)
            elif isinstance(n, int) or isinstance(n, float):
                # If the element is a number, get its summary
                summary = await get_leaf_summary_async(str(n), min_len=self.leaf_min_len)
            elif isinstance(n, dict):
                # If the dict has a 's' key, use it as the summary
                summary = n.get('s', '')
            elif isinstance(n, list):
                # If the element is a list, get its summary
                summary = await get_list_summary_async(n)
            elif n is None:
                # If the element is None, skip it
                summary = ""
            else:
                raise ValueError(f"Unsupported element type: {type(n)} in {n}")
            list_summary.append(summary)
            
        # Concatenate all elements and summarize
        # concatenated = " ".join(list_summary)
        # response = get_text_summary_response(concatenated, model="gemma3:27b", role="user", lang='zh')
        # if response.message.content:
        #     return response.message.content
        # else:
        #     # If the response is empty, raise an exception
        #     raise ValueError("Summary response is empty. Please check the input data.")
        return await get_leaf_summary_async(" ".join(list_summary), min_len=self.leaf_min_len)

    async def summary_nodewline_main(action: Optional[Callable] = None) -> None:
        """
        Main function to walk the AST and summarize nodes.
        This function will be called by the walk method.
        """
        if not self.ast_json:
            raise ValueError("raw_json content is empty. Cannot walk the AST and summarize.")
        if action is None:
            action = self.__class__.identity

        config_ast = jsoncfg.load_config(str(self.ast_json_file))
        ast_dict = json.loads(self.ast_json)
        assert isinstance(config_ast, ConfigJSONObject), f"AST should be a dictionary, got {type(config_ast)}"
        config_blocks = config_ast['blocks']
        blocks = ast_dict['blocks']

        _ , blocks = await summary_node_pair_async(config_blocks, blocks)
        ast_dict['blocks'] = blocks
        if ast_dict.get('title') is None:
            # If the title is not set, use the file name as the title
            if self.title is None:
                self.title = str(self.root_path)
        ast_dict['title'] = self.title  # Add the title to the AST
        ast_dict['file_path'] = str(self.file_path)  # Add the file path to the AST

        assert isinstance(blocks, list), f"Expected a list of blocks, got {type(blocks)}"
        dict_summary = [b['s'] for b in blocks if isinstance(b, dict) and 's' in b]
        dict_summary = [ast_dict['title']] + dict_summary  # Add the title to the summary list
        # the summary of the document from the summaries in the list of blocks
        if not ast_dict['blocks'] or dict_summary == []:
            # If the blocks are empty, set the summary to an empty string
            ast_dict['summary'] = ""
            # If the summary is empty, set the AST JSON to an empty string
            self.ast_json = json.dumps(ast_dict, ensure_ascii=False).encode("utf-8").decode("utf-8")
        else:
            # If the blocks are not empty, set the summary to the concatenated summaries
            doc_summary = await get_leaf_summary_async(" ".join(dict_summary), min_len=self.leaf_min_len)
            ast_dict['summary'] = doc_summary
            # Convert the summarized AST back to JSON
            self.ast_json = json.dumps(ast_dict, ensure_ascii=False).encode("utf-8").decode("utf-8")

    async def summary_node_pair_async(config_node: ConfigNode, 
                                    node: dict | list | str | int | float | bool | None) \
                                    -> tuple[ConfigNode, dict | list | str | int | float | bool | None]:
        '''
        Given a string node, add key,value pair: node['s'] = node_summary, and return the node 
        '''
        if isinstance(node, dict):
            assert isinstance(config_node, ConfigJSONObject), f"Expected ConfigJSONObject, got {type(config_node)}\n" \
                f"config_node at line: {jsoncfg.node_location(config_node).line}"
            try:
                t = node["t"]
            except KeyError:
                raise ValueError(f"Node does not have a 't' key: {node}")
            if t == "Image":  # Image summary, the Image node is as defined in the pandoc AST
                summary = []
                # Get the image caption
                if isinstance(node['c'][1], list):
                    for item in node['c'][1]:
                        assert isinstance(item, dict), f"Expected dict in image caption list, got {type(item)} in {item}\n" \
                                            f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                            f"On line: {jsoncfg.node_location(config_node).line}"
                        # If the caption item is a nested structure, extract the text content
                        if isinstance(item.get('c'), str):
                            # summary.append(item['c'].strip())
                            pass
                        else:
                            assert isinstance(item.get('c'), list), f"Expected list in image caption item, got {type(item.get('c'))} in {item}\n" \
                                            f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                            f"On line: {jsoncfg.node_location(config_node).line}"
                            assert item.get('c') is not None, f"Image caption item is empty: {item}\n"
                            for chd in item.get('c'):  # type ignore
                                if isinstance(chd.get('c'), str):
                                    # summary.append(chd['c'].strip())
                                    pass
                                else:
                                    raise ValueError(f"Allow only one level of caption formatting {type(chd.get('c'))} in {chd}\n" \
                                            f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                            f"On line: {jsoncfg.node_location(config_node).line}")
                            
                else:
                    raise ValueError(f"Invalid image caption format: {node['c'][1]}\n" \
                                    f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                    f"On line: {jsoncfg.node_location(config_node).line}")
                # Get the image link and summarize the image
                try:
                    # summary.append(node['c'][0])  # The first element are defined to be attributes of the image rendering, i.e. content-irrelevant.
                    # If the node is an image, get its link
                    image_link = self.root_path / node['c'][2][0]  # Assuming the image link is in the third element of the list
                    image_link = str(image_link)
                    if image_link and re.search(image_link_pattern, image_link):  # re.match leads to empty match if there's spaces in the path!
                        # If the node is an image link, get its summary using unified function
                        response_content = await get_image_summary_async(
                            client=self.ollama_client,
                            image_link=image_link,
                            model="gemma3:27b",
                            role="user",
                            lang='zh'
                            )
                        # summary.append(response.message.content)
                        node["s"] = response_content
                    else:
                        # If the node is not an image link, summarize its content
                        raise ValueError(f"Invalid image link: {image_link}")
                    # Get the summary of the image caption

                except (IndexError, KeyError):
                    # Handle cases where the image link is not in the expected format
                    raise ValueError(f"Invalid image node structure: {node}\n" \
                                    f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                    f"On line: {jsoncfg.node_location(config_node).line}")
                # The second element is the image title
                # summary.append(node['c'][2][1])  # The second element is the image title

                # try:
                #     response_txt = await get_text_summary_response_async(
                #         client=self.llm_client,
                #         content=" ".join(summary),
                #         model="gemma3:27b",
                #         role="user",
                #         lang='zh'
                #     )
                #     node["s"] = response_txt.message.content
                # except Exception as e:
                #     raise ValueError(f"Error summarizing image node: {node}\n" \
                #                     f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                #                     f"On line: {jsoncfg.node_location(config_node).line}\n" \
                #                     f"Error: {e}")

                print(f"Summarize image: {image_link} on line {jsoncfg.node_location(config_node).line}")
            elif t == "Cite" or t == "AlignDefault" or t == "ColWidth" :  # Quoted node will be ignored
                node["s"] = ""  # Set the summary to an empty string
            else: # TextBlock summary
                c = node.get("c", None)
                if not c:
                    node["s"] = ""
                else:
                    dict_summary = []
                    for (ckey,cvalue), (key, value) in zip(config_node, node.items()): # get summary of the values (content)
                        if key == "t":
                            continue
                        if isinstance(cvalue, ConfigJSONArray):  # get the summary of the string list
                            assert isinstance(value, list), f"Expected a list for key {key}, got {type(value)} in {value}\n" \
                                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                f"key {ckey} On line: {jsoncfg.node_location(cvalue).line}"
                            if value == [] or cvalue is None:
                                # If the list is empty, skip it
                                continue
                            # If the value is a list, summarize each element
                            node[key] = []
                            # config_node = []
                            for citem, item in zip(cvalue, value):
                                try:
                                    _, child = await summary_node_pair_async(citem, item)
                                    node[key].append(child)
                                except Exception as e:
                                    raise ValueError(f"Error summarizing list item: {item}\n" \
                                                    f"ConfigNode: {citem} of type {type(citem)}.\n" \
                                                    f"On line: {jsoncfg.node_location(citem).line}\n" \
                                                    f"Error: {e}")
                                # config_node.append(config_child)
                            dict_summary.append(await get_list_summary_async(value))
                        elif isinstance(cvalue, ConfigJSONObject):
                            assert isinstance(value, dict), f"Expected a dict for key {key}, got {type(value)} in {value}\n" \
                                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                f"key {ckey} On line: {jsoncfg.node_location(cvalue).line}"
                            try:
                                config_child, child = await summary_node_pair_async(cvalue, value)  # insert the value['s']
                            except Exception as e:
                                raise ValueError(f"Error summarizing dict item: {value}\n" \
                                                f"ConfigNode: {cvalue} of type {type(cvalue)}.\n" \
                                                f"On line: {jsoncfg.node_location(cvalue).line}\n" \
                                                f"Error: {e}")
                            assert isinstance(child,dict) and 's' in child, f"Expected dict with 's' key, got {child}\n" \
                                f"ConfigNode: {config_child} of type {type(config_child)}.\n" \
                                f"On line: {jsoncfg.node_location(config_child).line}"
                            dict_summary.append(child['s'])

                        elif value is None or value == "":
                            # If the value is None, skip it
                            continue
                        elif isinstance(cvalue, ConfigJSONScalar):
                            assert isinstance(value, (str, int, float)), f"Expected a scalar for key {key}, got {type(value)} in {value}\n" \
                                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                f"key {ckey} On line: {jsoncfg.node_location(cvalue).line}"
                            # If the value is a scalar, summarize it
                            if isinstance(value, str):
                                value = value.strip()
                            dict_summary.append(await get_leaf_summary_async(str(value),min_len=self.leaf_min_len))
                    # get the summary of the node
                    if dict_summary:  # type: ignore
                        # If there are summaries, concatenate them
                        node["s"] = await get_leaf_summary_async(" ".join(dict_summary),min_len=self.leaf_min_len)
                        # node["s"] = get_text_summary_response(
                        #     " ".join(dict_summary), model="gemma3:27b", role="user", lang='zh'
                        # ).message.content
                    else:
                        # If no summaries, set to empty string
                        node["s"] = ""

                # if t is table
                if t == "Table":
                    print(f"{self.file_path} Summarize table: {self.table_count} on line {jsoncfg.node_location(config_node).line}")
                    self.table_count += 1
                elif t == "Section":
                    print(f"{self.file_path} Summarize section: {self.section_count} on line {jsoncfg.node_location(config_node).line}")
                    self.section_count += 1

        elif isinstance(node, list):
            assert isinstance(config_node, ConfigJSONArray), f"Expected ConfigJSONArray, got {type(config_node)}" \
                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                f"On line: {jsoncfg.node_location(config_node).line}"
            new_node = []
            for citem, item in zip(config_node, node):
                if isinstance(item, (str, int, float, bool)):
                    child = str(item).strip()
                elif isinstance(item, (dict, list)):
                    try:
                        _, child = await summary_node_pair_async(citem, item)
                    except Exception as e:
                        raise ValueError(f"Error summarizing list item: {item}\n" \
                                        f"ConfigNode: {citem} of type {type(citem)}.\n" \
                                        f"On line: {jsoncfg.node_location(citem).line}\n" \
                                        f"Error: {e}")
                # config_node.append(config_child)
                else: # item is None
                    child = item
                new_node.append(child)
            node = new_node
        elif isinstance(node, (str, int, float, bool)):
            assert isinstance(config_node, ConfigJSONScalar), f"Expected ConfigJSONScalar, got {type(config_node)}" \
                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                f"On line: {jsoncfg.node_location(config_node).line}"
            try:
                node_summary = await get_leaf_summary_async(str(node), min_len=self.leaf_min_len)
                node = node_summary
            except Exception as e:
                raise ValueError(f"Error summarizing node: {node}\n" \
                                f"ConfigNode: {config_node} of type {type(config_node)}.\n" \
                                f"On line: {jsoncfg.node_location(config_node).line}\n" \
                                f"Error: {e}")
        else:
            raise ValueError(f"Unsupported node type: {type(node)} in {node}\n" \
                            f"Unsupported ConfigNode: {config_node} of type {type(config_node)}." \
                            f"On line: {jsoncfg.node_location(config_node).line}")  

        return config_node, node

    async def summary_node_main(action: Optional[Callable] = None) -> None:
        """
        Main function to walk the AST and summarize nodes.
        This function will be called by the walk method.
        """
        if not self.ast_json:
            raise ValueError("raw_json content is empty. Cannot walk the AST and summarize.")
        if action is None:
            action = self.__class__.identity

        ast = json.loads(self.ast_json)
        blocks = ast.get("blocks", [])

        ast['blocks'] = await summary_node_async(blocks)
        if ast.get('title') is None:
            # If the title is not set, use the file name as the title
            if self.title is None:
                self.title = str(self.root_path)
        ast['title'] = self.title  # Add the title to the AST
        ast['file_path'] = str(self.file_path)  # Add the file path to the AST

        assert isinstance(blocks, list), f"Expected a list of blocks, got {type(blocks)}"
        dict_summary = [b['s'] for b in blocks if isinstance(b, dict) and 's' in b]
        dict_summary = [ast['title']] + dict_summary  # Add the title to the summary list
        # the summary of the document from the summaries in the list of blocks
        if not ast['blocks'] or dict_summary == []:
            # If the blocks are empty, set the summary to an empty string
            ast['summary'] = ""
            # If the summary is empty, set the AST JSON to an empty string
            self.ast_json = json.dumps(ast, ensure_ascii=False).encode("utf-8").decode("utf-8")
        else:
            # If the blocks are not empty, set the summary to the concatenated summaries
            doc_summary = await get_leaf_summary_async(" ".join(dict_summary), min_len=self.leaf_min_len)
            ast['summary'] = doc_summary
            # Convert the summarized AST back to JSON
            self.ast_json = json.dumps(ast, ensure_ascii=False).encode("utf-8").decode("utf-8")
        
    async def summary_node_async(node: dict | list) -> dict | list:
        '''
        Given a string node, add key,value pair: node['s'] = node_summary, and return the node 
        '''
        if isinstance(node, dict):
            try:
                t = node["t"]
            except KeyError:
                raise ValueError(f"Node does not have a 't' key: {node}")
            if t == "Image":  # Image summary, the Image node is as defined in the pandoc AST
                summary = []
                if (not node['c'][1] == []) and (node['c'][1][0] is not None) and (node['c'][1][0].get('c') is not None):
                    summary.append(node['c'][1][0]['c'])  # The content of the second element is the image caption
                try:
                    # summary.append(node['c'][0])  # The first element are defined to be attributes of the image rendering, i.e. content-irrelevant.
                    # If the node is an image, get its link
                    image_link = self.modelroot_path / node['c'][2][0]  # Assuming the image link is in the third element of the list
                    image_link = str(image_link)
                    if image_link and re.search(image_link_pattern, image_link):  # re.match leads to empty match if there's spaces in the path!
                        # If the node is an image link, get its summary
                        response = await get_image_summary_response_async(
                            client=self.ollama_client,
                            image_link=image_link,
                            model="gemma3:27b",
                            role="user",
                            lang='zh'
                            )
                        summary.append(response.message.content)
                    else:
                        # If the node is not an image link, summarize its content
                        raise ValueError(f"Invalid image link: {image_link}")
                    # Get the summary of the image caption

                except (IndexError, KeyError):
                    # Handle cases where the image link is not in the expected format
                    raise ValueError(f"Invalid image node structure: {node}")
                # The second element is the image title
                summary.append(node['c'][2][1])  # The second element is the image title

                response_txt = await get_text_summary_response_async(
                    client=self.openai_client,
                    content=" ".join(summary),
                    model="gemma3:27b",
                    role="user",
                    lang='zh'
                )
                node["s"] = response_txt.message.content

                print(f"Summarize image: {image_link}")
            elif t == "Cite" or t == "AlignDefault" or t == "ColWidth" :  # Quoted node will be ignored
                node["s"] = ""  # Set the summary to an empty string
            else: # TextBlock summary
                c = node.get("c", None)
                if not c:
                    node["s"] = ""
                else:
                    dict_summary = []
                    for key, value in node.items(): # get summary of the values (content)
                        if key == "t":
                            continue
                        if isinstance(value, list):  # get the summary of the string list
                            if value == []:
                                # If the list is empty, skip it
                                continue
                            # If the value is a list, summarize each element
                            node[key] = [
                                await summary_node_async(child)
                                if isinstance(child, (dict,list))
                                else child
                                for child in value
                            ]
                            dict_summary.append(await get_list_summary_async(value))
                        elif isinstance(value, dict):
                            child = await summary_node_async(value)  # insert the value['s']
                            assert isinstance(child, dict) and 's' in child, f"Expected dict with 's' key, got {child}"
                            dict_summary.append(child['s'])

                        elif value is None or value == "":
                            # If the value is None, skip it
                            continue
                        else:
                            if not isinstance(value, str):
                                # If the value is not a string, convert it to a string
                                value = str(value)
                            dict_summary.append(await get_leaf_summary_async(value,min_len=self.leaf_min_len))
                    # get the summary of the node
                    if dict_summary:  # type: ignore
                        # If there are summaries, concatenate them
                        node["s"] = await get_leaf_summary_async(" ".join(dict_summary),min_len=self.leaf_min_len)
                        # node["s"] = get_text_summary_response(
                        #     " ".join(dict_summary), model="gemma3:27b", role="user", lang='zh'
                        # ).message.content
                    else:
                        # If no summaries, set to empty string
                        node["s"] = ""

                # if t is table
                if t == "Table":
                    print(f"{self.file_path} Summarize table: {self.table_count}")
                    self.table_count += 1
                elif t == "Section":
                    print(f"{self.file_path} Summarize section: {self.section_count} section depth {node['c'][0]['c'][0]}")
                    self.section_count += 1

        elif isinstance(node, list):
            node = [
                await summary_node_async(child) if isinstance(child, (dict,list)) else child
                for child in node
            ]
        else:
            assert isinstance(node, str), f"Expected a string node, got {type(node)}, on json line"
            # If the node is a string, get its summary
            node_summary = await get_leaf_summary_async(node, min_len=self.leaf_min_len)
            node = node_summary

        return node

    # Run the summary_nodewline_main function asynchronously
    # asyncio.run(summary_nodewline_main(action))
    await summary_nodewline_main(action)
    return 


# %% ../nbs/01.core.dom.ipynb #02e63d20
@patch(cls_method=True)
def identity(cls: DOM, obj):
    """Return an object unchanged during traversal hooks.
    
    Args:
        obj: Object to return as-is.
    
    Returns:
        Any: The original object.
    """
    return obj


# %% ../nbs/01.core.dom.ipynb #8e3e37aa
async def analyze_one_document_async(md_file: Path, semaphore: asyncio.Semaphore) -> DOM:
    """Analyze one markdown document asynchronously and persist its semantics JSON.
    
    Args:
        md_file: Markdown file to analyze.
        semaphore: Concurrency guard used while processing the file.
    
    Returns:
        DOM: Processed DOM object with analysis status populated.
    """
    try:
        async with semaphore:  # Limit concurrent access to the semaphore
            print(f"Analyzing document: {md_file}")
            with warnings.catch_warnings(record=True) as w:
                warnings.simplefilter("always")
                dom = DOM(md_file, ollama_client=ollama_client, openai_client=openai_client)
                dom.setup()  # Load the Markdown content and convert it to JSON AST
                if w:
                    print(f"Warnings encountered while setting up DOM for {md_file}: {w}")
            if dom.semantics_json:
                dom.analysis_status.status = ResponseStatus.COMPLETED
                dom.analysis_status.exception = f"Document already analyzed: {md_file.stem}"
                return dom

            with warnings.catch_warnings(record=True) as w:
                warnings.simplefilter("always")
                await dom.textualize()  # Summarize the document
                if w:
                    print(f"Warnings encountered while textualizing DOM for {md_file}: {w}")
            if dom.file_path:
                semantics_json_file = md_file.parent / (str(md_file.stem) + "_semantics.json")
                semantics_json_file.write_text(dom.ast_json, encoding="utf-8")  # type: ignore
                dom.analysis_status.status = ResponseStatus.COMPLETED  # type: ignore
                dom.analysis_status.exception = f"Finished analyzing document: {md_file.stem}"
    except asyncio.CancelledError:
        dom.analysis_status.status = ResponseStatus.CANCELLED  # type: ignore
        dom.analysis_status.exception = f"Analysis cancelled for document: {md_file}"  # type: ignore
    except Exception as e:
        dom.analysis_status.status = ResponseStatus.ERROR  # type: ignore
        dom.analysis_status.exception = f"Error occurred while analyzing document: {md_file}, Error: {e}"  # type: ignore

    return dom  # type: ignore

# %% ../nbs/01.core.dom.ipynb #9a4ecfda
async def embed_one_document_async(md_file: Path, semaphore: asyncio.Semaphore) -> DOM:
    """Embed one markdown document asynchronously from its semantics JSON.
    
    Args:
        md_file: Markdown file whose semantics should be embedded.
        semaphore: Concurrency guard used while processing the file.
    
    Returns:
        DOM: Processed DOM object with embedding status populated.
    """
    try:
        async with semaphore:  # Limit concurrent access to the semaphore
            print(f"Analyzing document: {md_file}")
            with warnings.catch_warnings(record=True) as w:
                warnings.simplefilter("always")
                dom = DOM(md_file, ollama_client=ollama_client, openai_client=openai_client)
                dom.setup()  # Load the Markdown content and convert it to JSON AST
                if w:
                    print(f"Warnings encountered while setting up DOM for {md_file}: {w}")
            if not dom.semantics_json:
                dom.analysis_status.status = ResponseStatus.PENDING
                dom.analysis_status.exception = f"Document semantics not found: {md_file.stem}"
                return dom

            with warnings.catch_warnings(record=True) as w:
                warnings.simplefilter("always")
                await dom.embed()  # Summarize the document
                if w:
                    print(f"Warnings encountered while embedding DOM for {md_file}: {w}")
            dom.analysis_status.status = ResponseStatus.COMPLETED  # type: ignore
            dom.analysis_status.exception = f"Finished embedding document: {md_file.stem}"
    except asyncio.CancelledError:
        dom.analysis_status.status = ResponseStatus.CANCELLED  # type: ignore
        dom.analysis_status.exception = f"Embedding cancelled for document: {md_file}"  # type: ignore
    except Exception as e:
        dom.analysis_status.status = ResponseStatus.ERROR  # type: ignore
        dom.analysis_status.exception = f"Error occurred while embedding document: {md_file}, Error: {e}"  # type: ignore

    return dom  # type: ignore
